### ISSUE TITLE
Can't I select multiple models at once?

### ISSUE THREAD

**Issue by kbuwel** [SUC-DriverOld/MSST-WebUI#42]
It seems like there is an ensemble function, but it doesn't seem to be what I was thinking.
Is there no function to select several models that I want to use and process them all at once?
Are there any plans to add more functions?
It seems like it takes too much time to select models one by one.
I think it would be possible to reduce the time if it was possible to work on them all at once.

**Comment by SUC-DriverOld** [comment]
The current usage method of ensemble mode is as follows: users first need to use different models (2 or more) to process the same song, then upload all processing results (audio files) on the ensemble page, and then proceed with ensemble.

Due to the limited number of users actually using ensemble, I did not receive much feedback. The current ensemble code fully utilizes [the scripts](https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/ensemble.py) provided by ZFTurbo and has not been updated for six months. In response to your suggestion, I will consider adding something similar to a "preset" in the future to facilitate ensemble.

**Comment by SUC-DriverOld** [comment]
The current usage method of ensemble mode is as follows: users first need to use different models (2 or more) to process the same song, then upload all processing results (audio files) on the ensemble page, and then proceed with ensemble.

Due to the limited number of users actually using ensemble, I did not receive much feedback. The current ensemble code fully utilizes [the scripts](https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/ensemble.py) provided by ZFTurbo and has not been updated for six months. I will consider adding something similar to a "preset" in the future to facilitate ensemble. But at present, I have no plans to update ensemble.

In fact, adding fast processing scripts does not significantly speed up the processing speed, it can only eliminate the tedious process of manually selecting models and uploading audio to the ensemble page(these don't cost some time). The model inference takes the longest actual time and cannot be reduced.

**Comment by kbuwel** [comment]
I think the work of answering is inefficient.
It is a work that does not consider the capacity of the storage device.
I think it is inefficient and takes up a lot of space, especially when working with many files.

**Comment by SUC-DriverOld** [comment]
When dealing with multiple files, even according to your proposed idea, the cache in the intermediate process cannot be reduced.  If you feel that it takes up too much space, you can consider exporting MP3 or FLAC files and then perform ensemble. But these **occupied spaces as cache cannot be reduced** in fact.

**Comment by SUC-DriverOld** [comment]
In addition, the actual function of ensemble is to transform multiple audio files into a better quality audio according to a certain algorithm. It cannot handle multiple files directly.

**Comment by kbuwel** [comment]
What I want to say is not cache. I will write down what I understand from Google Translate's answer.
Here is what I understand from the answer.
Let's say you have an audio file.
This audio file is made into a file with, for example, a karaoke model, a vocal model, and noise removed.
And it seems that you use the ensemble function to make it into a single file.
This is inefficient and requires a lot of storage.
What I am talking about here is definitely not cache.
I think cache is inevitable.
It is inefficient and wastes storage to separate the original file into a karaoke model, then separate the vocal model from the original file, and then separate the original file into another model.
In uvr, you do the following:
Select the desired model. Kim_Vocal_2.onnx, mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956_config.yaml, model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt
After selecting these 3 models, load the audio files and work on them at once.
I think that working like this will save a lot of storage space and save time.
The current method is too inefficient and a waste of storage space.
Again, I'm not talking about cache capacity.

**Comment by SUC-DriverOld** [comment]
What you described is not the function of ensemble, this is a preset function, and it is available in the webui. As long as you set the process in advance, you can obtain the results processed by multiple models with just one click, just as you said. And our preset process is more advanced than UVR's.

**Comment by SUC-DriverOld** [comment]
You can go to the page shown below to create a preset process. In the following figure, I use the `bs_roformer-ep_317_str12.9755.ckpt` and `dererb_cel_mand_roformer_less_aggressive_anvuew_sdr_18.8050.ckpt` models as examples.
![image](https://github.com/user-attachments/assets/02340b5b-03f5-4308-b02d-ee931f5dc1c4)
Then, save the presets and go to the page shown below to run this preset flow.
![image](https://github.com/user-attachments/assets/2bed261e-853d-47f5-b9a8-d11fc4ebeeb7)
You can upload multiple audio files for batch processing. The program will process based on the presets you have created and selected.

**Comment by SUC-DriverOld** [comment]
I understand what you mean. But currently, I am unable to add the feature you mentioned as there are too many areas that need to be modified. In the future, I may consider.

**Comment by SUC-DriverOld** [comment]
I understand what you mean. But currently, there are too many codes that need to be modified. I'll add this feature in latter version.
